# Generated by Django 3.2.8 on 2021-11-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(upload_to='static/ecommerce/order/'),
        ),
    ]
